// ============================================================
// IPTV Suisse - Constants & Configuration
// ============================================================

export const SITE_CONFIG = {
  name: 'Meilleur IPTV Suisse',
  domain: 'meilleur.iptv-suisse.com',
  url: 'https://meilleur.iptv-suisse.com',
  email: 'contact@meilleur.iptv-suisse.com',
  // TODO: Replace with real phone number before go-live
  phone: '+41 XX XXX XX XX',
  // TODO: Replace with real WhatsApp number before go-live
  whatsapp: 'https://wa.me/41XXXXXXXXX',
  defaultLocale: 'fr' as const,
  locales: ['fr', 'de'] as const,
} as const;

// City pages for internal linking & SEO
export const CITIES = [
  'geneve', 'zurich', 'lausanne', 'bern', 'basel',
  'winterthur', 'st-gallen', 'lugano', 'biel', 'luzern',
  'fribourg', 'neuchatel', 'thun',
] as const;

export const STATS = {
  channels: '37,000+',
  movies: '40,000+',
  series: '17,000+',
  uptime: '99.9%',
  customers: '37,000+',
  supportHours: '24/7',
  activationTime: '2h',
} as const;

// Plans data — all 12 plans from WordPress, grouped by device count
export const PLANS = [
  // ── 1 Screen Plans ──────────────────────────────────────
  {
    id: '1',
    slug: 'abonnement-iptv-3-mois',
    duration: 3,
    price: 35.99,
    original_price: 51.41,
    devices: 1,
    is_popular: false,
    is_active: true,
    payment_link: 'https://iptvsuisse.ch/standard',
    image: '/images/plans/abonnement-iptv-3-mois.png',
    name_fr: 'Abonnement IPTV 3 Mois',
    name_de: 'IPTV Abo 3 Monate',
    description_fr: 'Idéal pour découvrir notre service premium',
    description_de: 'Ideal zum Entdecken unseres Premium-Service',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7'],
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    slug: 'abonnement-iptv-6-mois',
    duration: 6,
    price: 44.99,
    original_price: 64.27,
    devices: 1,
    is_popular: false,
    is_active: true,
    payment_link: 'https://iptvsuisse.ch/express',
    image: '/images/plans/abonnement-iptv-6-mois.png',
    name_fr: 'Abonnement IPTV 6 Mois',
    name_de: 'IPTV Abo 6 Monate',
    description_fr: "L'équilibre parfait entre durée et prix",
    description_de: 'Die perfekte Balance zwischen Dauer und Preis',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7'],
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    slug: 'abonnement-iptv-12-mois',
    duration: 12,
    price: 59.99,
    original_price: 85.70,
    devices: 1,
    is_popular: true,
    is_active: true,
    payment_link: 'https://supremeiptv.ch/Premium',
    image: '/images/plans/abonnement-iptv-12-mois.png',
    name_fr: 'Abonnement IPTV 12 Mois',
    name_de: 'IPTV Abo 12 Monate',
    description_fr: 'Notre meilleur rapport qualité-prix — Recommandé',
    description_de: 'Unser bestes Preis-Leistungs-Verhältnis — Empfohlen',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7', 'free_updates'],
    created_at: new Date().toISOString(),
  },
  // ── 2 Screens Plans ─────────────────────────────────────
  {
    id: '4',
    slug: '2-ecrans-3-mois',
    duration: 3,
    price: 53.99,
    original_price: 77.13,
    devices: 2,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/2-ecrans-3-mois.png',
    name_fr: '2 Écrans 3 Mois',
    name_de: '2 Bildschirme 3 Monate',
    description_fr: 'Partagez votre abonnement sur 2 appareils simultanément',
    description_de: 'Teilen Sie Ihr Abo auf 2 Geräten gleichzeitig',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7'],
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    slug: '2-ecrans-6-mois',
    duration: 6,
    price: 67.99,
    original_price: 97.13,
    devices: 2,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/2-ecrans-6-mois.png',
    name_fr: '2 Écrans 6 Mois',
    name_de: '2 Bildschirme 6 Monate',
    description_fr: '6 mois de streaming sur 2 écrans',
    description_de: '6 Monate Streaming auf 2 Bildschirmen',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7'],
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    slug: '2-ecrans-12-mois',
    duration: 12,
    price: 89.99,
    original_price: 128.56,
    devices: 2,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/2-ecrans-12-mois.png',
    name_fr: '2 Écrans 12 Mois',
    name_de: '2 Bildschirme 12 Monate',
    description_fr: 'Le meilleur prix pour 2 écrans — 1 an complet',
    description_de: 'Bester Preis für 2 Bildschirme — 1 ganzes Jahr',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7', 'free_updates'],
    created_at: new Date().toISOString(),
  },
  // ── 3 Screens Plans ─────────────────────────────────────
  {
    id: '7',
    slug: '3-ecrans-3-mois',
    duration: 3,
    price: 80.99,
    original_price: 115.70,
    devices: 3,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/3-ecrans-3-mois.png',
    name_fr: '3 Écrans 3 Mois',
    name_de: '3 Bildschirme 3 Monate',
    description_fr: 'Pour toute la famille — 3 appareils simultanés',
    description_de: 'Für die ganze Familie — 3 gleichzeitige Geräte',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7'],
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    slug: '3-ecrans-6-mois',
    duration: 6,
    price: 101.99,
    original_price: 145.70,
    devices: 3,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/3-ecrans-6-mois.png',
    name_fr: '3 Écrans 6 Mois',
    name_de: '3 Bildschirme 6 Monate',
    description_fr: '6 mois pour 3 écrans — idéal pour les familles',
    description_de: '6 Monate für 3 Bildschirme — ideal für Familien',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7'],
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    slug: '3-ecrans-12-mois',
    duration: 12,
    price: 134.99,
    original_price: 192.84,
    devices: 3,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/3-ecrans-12-mois.png',
    name_fr: '3 Écrans 12 Mois',
    name_de: '3 Bildschirme 12 Monate',
    description_fr: '1 an complet pour 3 écrans — meilleur prix familial',
    description_de: '1 ganzes Jahr für 3 Bildschirme — bester Familienpreis',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7', 'free_updates'],
    created_at: new Date().toISOString(),
  },
  // ── 4 Screens Plans ─────────────────────────────────────
  {
    id: '10',
    slug: '4-ecrans-3-mois',
    duration: 3,
    price: 107.99,
    original_price: 154.27,
    devices: 4,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/4-ecrans-3-mois.png',
    name_fr: '4 Écrans 3 Mois',
    name_de: '4 Bildschirme 3 Monate',
    description_fr: 'Maximum de connexions — 4 appareils simultanés',
    description_de: 'Maximale Verbindungen — 4 gleichzeitige Geräte',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7'],
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    slug: '4-ecrans-6-mois',
    duration: 6,
    price: 134.99,
    original_price: 192.84,
    devices: 4,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/4-ecrans-6-mois.png',
    name_fr: '4 Écrans 6 Mois',
    name_de: '4 Bildschirme 6 Monate',
    description_fr: '6 mois sur 4 écrans pour toute la maison',
    description_de: '6 Monate auf 4 Bildschirmen für das ganze Haus',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7'],
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    slug: '4-ecrans-12-mois',
    duration: 12,
    price: 179.99,
    original_price: 257.13,
    devices: 4,
    is_popular: false,
    is_active: true,
    payment_link: '',
    image: '/images/plans/4-ecrans-12-mois.png',
    name_fr: '4 Écrans 12 Mois',
    name_de: '4 Bildschirme 12 Monate',
    description_fr: 'Offre ultime — 4 écrans pendant 1 an complet',
    description_de: 'Ultimatives Angebot — 4 Bildschirme für 1 ganzes Jahr',
    features: ['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7', 'free_updates'],
    created_at: new Date().toISOString(),
  },
] as const;
