-- ============================================================
-- IPTV Dark — full plan catalog: 1–4 schermen × 3/6/12 maanden (12 rows).
-- Upserts by slug; preserves existing payment_link and checkout_mode.
-- ============================================================

INSERT INTO plans (
  slug,
  duration,
  price,
  original_price,
  devices,
  features,
  is_popular,
  is_active,
  name_fr,
  name_de,
  description_fr,
  description_de,
  sort_order,
  checkout_mode,
  payment_link
)
VALUES
  (
    'abonnement-iptv-3-maanden',
    3,
    35.99,
    51.41,
    1,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7']::text[],
    FALSE,
    TRUE,
    'IPTV-abonnement 3 maanden',
    'IPTV Abo 3 Monate',
    'Ideaal om onze premium service uit te proberen',
    'Ideal zum Entdecken unseres Premium-Service',
    1,
    'form_only',
    ''
  ),
  (
    'abonnement-iptv-6-maanden',
    6,
    44.99,
    64.27,
    1,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7']::text[],
    FALSE,
    TRUE,
    'IPTV-abonnement 6 maanden',
    'IPTV Abo 6 Monate',
    'De beste balans tussen looptijd en prijs',
    'Die perfekte Balance zwischen Dauer und Preis',
    2,
    'form_only',
    ''
  ),
  (
    'abonnement-iptv-12-maanden',
    12,
    59.99,
    85.70,
    1,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7', 'free_updates']::text[],
    TRUE,
    TRUE,
    'IPTV-abonnement 12 maanden',
    'IPTV Abo 12 Monate',
    'Onze beste prijs-kwaliteit — aanbevolen',
    'Unser bestes Preis-Leistungs-Verhältnis — Empfohlen',
    3,
    'form_only',
    ''
  ),
  (
    '2-schermen-3-maanden',
    3,
    53.99,
    77.13,
    2,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7']::text[],
    FALSE,
    TRUE,
    '2 schermen — 3 maanden',
    '2 Bildschirme 3 Monate',
    'Deel je abonnement op 2 apparaten tegelijk',
    'Teilen Sie Ihr Abo auf 2 Geräten gleichzeitig',
    4,
    'form_only',
    ''
  ),
  (
    '2-schermen-6-maanden',
    6,
    67.99,
    97.13,
    2,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7']::text[],
    FALSE,
    TRUE,
    '2 schermen — 6 maanden',
    '2 Bildschirme 6 Monate',
    'Zes maanden streamen op twee schermen',
    '6 Monate Streaming auf 2 Bildschirmen',
    5,
    'form_only',
    ''
  ),
  (
    '2-schermen-12-maanden',
    12,
    89.99,
    128.56,
    2,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7', 'free_updates']::text[],
    FALSE,
    TRUE,
    '2 schermen — 12 maanden',
    '2 Bildschirme 12 Monate',
    'Beste prijs voor twee schermen — een vol jaar',
    'Bester Preis für 2 Bildschirme — 1 ganzes Jahr',
    6,
    'form_only',
    ''
  ),
  (
    '3-schermen-3-maanden',
    3,
    80.99,
    115.70,
    3,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7']::text[],
    FALSE,
    TRUE,
    '3 schermen — 3 maanden',
    '3 Bildschirme 3 Monate',
    'Voor het hele gezin — drie apparaten tegelijk',
    'Für die ganze Familie — 3 gleichzeitige Geräte',
    7,
    'form_only',
    ''
  ),
  (
    '3-schermen-6-maanden',
    6,
    101.99,
    145.70,
    3,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7']::text[],
    FALSE,
    TRUE,
    '3 schermen — 6 maanden',
    '3 Bildschirme 6 Monate',
    'Zes maanden voor drie schermen — ideaal voor gezinnen',
    '6 Monate für 3 Bildschirme — ideal für Familien',
    8,
    'form_only',
    ''
  ),
  (
    '3-schermen-12-maanden',
    12,
    134.99,
    192.84,
    3,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7', 'free_updates']::text[],
    FALSE,
    TRUE,
    '3 schermen — 12 maanden',
    '3 Bildschirme 12 Monate',
    'Een vol jaar voor drie schermen — beste gezinsdeal',
    '1 ganzes Jahr für 3 Bildschirme — bester Familienpreis',
    9,
    'form_only',
    ''
  ),
  (
    '4-schermen-3-maanden',
    3,
    107.99,
    154.27,
    4,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7']::text[],
    FALSE,
    TRUE,
    '4 schermen — 3 maanden',
    '4 Bildschirme 3 Monate',
    'Maximaal parallel — vier apparaten tegelijk',
    'Maximale Verbindungen — 4 gleichzeitige Geräte',
    10,
    'form_only',
    ''
  ),
  (
    '4-schermen-6-maanden',
    6,
    134.99,
    192.84,
    4,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7']::text[],
    FALSE,
    TRUE,
    '4 schermen — 6 maanden',
    '4 Bildschirme 6 Monate',
    'Zes maanden op vier schermen voor het hele huishouden',
    '6 Monate auf 4 Bildschirmen für das ganze Haus',
    11,
    'form_only',
    ''
  ),
  (
    '4-schermen-12-maanden',
    12,
    179.99,
    257.13,
    4,
    ARRAY['premium_server', 'all_channels', 'hd_4k', 'replay_vod', 'all_devices', 'support_24_7', 'free_updates']::text[],
    FALSE,
    TRUE,
    '4 schermen — 12 maanden',
    '4 Bildschirme 12 Monate',
    'Topdeal — vier schermen voor een vol jaar',
    'Ultimatives Angebot — 4 Bildschirme für 1 ganzes Jahr',
    12,
    'form_only',
    ''
  )
ON CONFLICT (slug) DO UPDATE SET
  duration = EXCLUDED.duration,
  price = EXCLUDED.price,
  original_price = EXCLUDED.original_price,
  devices = EXCLUDED.devices,
  features = EXCLUDED.features,
  is_popular = EXCLUDED.is_popular,
  is_active = EXCLUDED.is_active,
  name_fr = EXCLUDED.name_fr,
  name_de = EXCLUDED.name_de,
  description_fr = EXCLUDED.description_fr,
  description_de = EXCLUDED.description_de,
  sort_order = EXCLUDED.sort_order,
  updated_at = NOW();
